name: stock

dependencies:
  - pip=22.2.2
#<<<<<<< HEAD
  - python=3.8.5
#=======
  - python==3.8.5
#>>>>>>> f5d3817 (yml change)

  - pip:
      - matplotlib
      - pandas
#<<<<<<< HEAD
      - flask
#=======
#>>>>>>> f5d3817 (yml change)
      - requests
      - scikit-learn
      - joblib
      - requests-html
      - yahoo-fin
      - google-cloud-storage
      - google-api-python-client
      - google-auth
      - google-auth-httplib2
#<<<<<<< HEAD
      - GitPython

#=======
      - GitPython #optional but required in my new version of the app
#>>>>>>> f5d3817 (yml change)

